name: php cs fixer

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          working-directory: tools/php-cs-fixer
      - name: Check code style
        run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --allow-risky=yes -vvv --show-progress=none -q

