name: review

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: '--no-scripts'
      - name: Install deptrac dependencies
        uses: "ramsey/composer-install@v2"
        with:
          working-directory: tools/deptrac
      - name: Phpstan
        run: ./vendor/bin/phpstan --no-progress --memory-limit=1g analyse
      - name: Deptrac
        run: tools/deptrac/vendor/bin/deptrac --no-progress
      - name: Phpunit
        run: ./vendor/bin/phpunit
